@startuml
'https://plantuml.com/class-diagram

class ListaEnlazada {
-primero:ElementoLE
+isVacia():boolean
+vaciar()
-add(el:ElementoLE):int
+add(s:String)
+add(o:Object)
+insert(s:String,posicion:int)
+insert(o:Object,posicion:int)
+del(posicion:int):int
+getNumeroElementos():int
+getPosicion(el:ElementoLE):int
+getPrimero():ElementoLE
+getUltimo():ElementoLE
+getSiguiente(el:ElementoLE):ElementoLE
+getElemento(posicion:int):ElementoLE
}

class ElementoLE {
-siguiente:ElementoLE
-data:Object
-insertarmeEn(el:ElementoLE)
-getSiguiente():ElementoLE
+getData():Object
+setData():Object
}

ListaEnlazada --> ElementoLE:primero
ElementoLE --> ElementoLE:siguiente


@enduml